on:
  workflow_dispatch
jobs:
  c3_files_cleanup:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
          env:
              ACCESS_TOKEN: '${{ secrets.ACCESS_TOKEN }}'
        - run: ls
        - run: |
            git config --global user.email "sqush.bot@squshy.co"
            git config --global user.name "sqush.bot"
            git config --global credential.helper cache
            git switch -c c3_reformat
            git push --set-upstream origin c3_reformat
        - run: python formatC3.py --version ${{ github.sha }}
        - run: |
            git add .
            git commit -m "Automated update: reformatting files for c3 - $(date)"
            git push
        - name: Create Pull Request
          uses: actions/github-script@v6
          with:
            script: |
              const { repo, owner } = context.repo;
              const result = await github.rest.pulls.create({
                title: '[AUTOMATED] c3 files update',
                owner,
                repo,
                head: '${{ github.ref_name }}',
                base: 'develop',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script).'
                ].join('\n')
              });
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: result.data.number,
                labels: ['feature', 'automated pr']
              });